AWS:
  ACCESS_KEY_ID: ""
  SECRET_ACCESS_KEY: ""
  SESSION_TOKEN: ""
  REGION: ""

VALIDATION:
  SOURCE_BUCKET: ""
  DESTINATION_BUCKET: ""
  ORGANIZATION: ""
  REPO_NAME: ""
  FILES_TO_VALIDATE:
    - "transformations1.py"
  ACCESS_TOKEN: ""
  PERMISSIONS:
#    StackSet-EMR-Role: ["CloudWatchFullAccess", "AmazonEC2FullAccess", "AmazonS3FullAccess", "AmazonSSMFullAccess", "AmazonSageMakerFullAccess", "AmazonElasticMapReduceRole"]
    StackSet-EMR-Role:
      - "CloudWatchFullAccess"
      - "AmazonEC2FullAccess"
      - "AmazonS3FullAccess"
      - "AmazonSSMFullAccess"
      - "AmazonSageMakerFullAccess"
      - "AmazonElasticMapReduceRole"

INFRA:
  GITHUB_ORGANIZATION: ""
  GITHUB_REPOSITORY: ""
  GITHUB_WORKFLOW: ""
  GITHUB_EVENT_TYPE: ""

ETL:
  S3_INPUT_BUCKET_NAME: ""
  AWS_REGION: ""
  TRANSFORMATION_FOLDER_PATH: ""
  S3_BUCKET_INPUT_PATH: ""
  S3_BUCKET_TEMP_OUTPUT_PATH: ""
  S3_BUCKET_FINAL_OUTPUT_PATH: ""
  TRANSFORMATION_FOLDER: ""
  BOAT: ""
  INPUT_FOLDER: ""

experiment:
  meta:
    name: MyFirstExperiment
  model:
    family: resnet
    n_layers: 151
  training:
    batch_size: 256
    epochs: 10000