AWS:
  ACCESS_KEY_ID: 
  SECRET_ACCESS_KEY: 
  SESSION_TOKEN: 
  REGION: 

VALIDATION: 
  PERMISSIONS:
    StackSet-EMR-Role:
      - CloudWatchFullAccess
      - AmazonEC2FullAccess
      - AmazonS3FullAccess
      - AmazonSSMFullAccess
      - AmazonSageMakerFullAccess
      - AmazonElasticMapReduceRole

INFRA:
  GITHUB_ORGANIZATION: DISHDevEx
  GITHUB_REPOSITORY: luminex-application
  GITHUB_WORKFLOW: create-emr-cft.yml
  GITHUB_EVENT_TYPE: create-emr-cft

ETL:
  S3_BUCKET_TEMP: luminex-application-files
  AWS_REGION: us-east-1
  TRANSFORMATION_FOLDER_PATH: DISHDevEx/luminex-transformation
  BOAT: luminex

EXPERIMENT:
  META:
    NAME: MyFirstExperiment
  MODEL:
    FAMILY: resnet
    N_LAYERS: 151
    NESTED_FAMILY:
      ITEMS:
        - CloudWatchFullAccess
        - AmazonEC2FullAccess
  TRAINING:
    BATCH_SIZE: 256
    EPOCHS: 10000