AWS:
  ACCESS_KEY_ID: ASIAVFTSQ26XHHC3SOSE
  SECRET_ACCESS_KEY: MNpWp7OBGoaV7pi4RBOLzauUC9wFAoX9rZOD1K8c
  SESSION_TOKEN: IQoJb3JpZ2luX2VjEM3//////////wEaCXVzLXdlc3QtMiJHMEUCIQC6fZmLSGRcG+/C48rohDWyHnXEGquORUHCxQjVld6XBgIgBEpfuC6mGfm+spg52cP6ST/O8OdRLYFiHpmwHDxJ3q4qmQMIZhAAGgwzNTU2NDg3MjI4NjIiDGjsG93qnQgXigUWqSr2AnBXX+heSug3QNhrodbMYcPPc+nlSb9Wj5jgyv90/YjbBLQEFTScpMHgSe+7+MUAaR0uT7oF60ALntUhUrswooNGuAmdry5CC4BdzgfI853VVaM8DFWfNv/MrcEat1OBAhOYO1F8MkfH/hYdnHd0cV0W7t/TrrbMBZIzQKDI/eBIRPDxq9EMGQUxHQ4FOPd8xsjWl9hwDjspY95FmsUkWABmuOoMn5jBuqsun4umTuCamd/6rBcDd1bZ4meFXzY/ivVYpZBTTMeHn6jlNcor5O+0pnNXkvtqNLOguCe1v0E8apmpR4HcZFRufl+GO7NPN8tdqvpWgoa8CRTA7z7XQFmNZd0gXRlKCFFS0kDxPR5xpAp7FBJWIkSimilNXBVKQa+iZfUuk1WHgB9XamYjZ9Eqtvld5msYU9W0AZ7pq/4NIHORjabt8uM5YxafD+cYKPyfoBa/cNM4mt5E8mTNFKXr4H+Q9oegSX6vHC9cSSIToVDFzYPwMKqN16wGOqYBPHLbgY67Q8hEHO8I5zGdT9DohC1wsNSUX47/dh27H3mYyGJWh4YkIjTm3KdaVNIUbdQQGY4sl1U0C+mpSPclWsxaLp3tJB8vjiEiob6rPd60Jt1vPnBfUoSF5HqSsvlQG1nHtpiBvknMHAjoCHjh3xhSDdci61/26h0iC87FOAniKvEN8AaS0ENCLzne9XcQjtV8LiklZ91fACl9aTjN+xfeTM/LPQ==
  REGION: us-east-1

VALIDATION:
  SOURCE_BUCKET:
  DESTINATION_BUCKET:
  ORGANIZATION: DISHDevEx
  REPO_NAME: luminex-transformation
  FILES_TO_VALIDATE:
    - transformations1.py
  ACCESS_TOKEN:
  PERMISSIONS:
    STACKSETEMRROLE:
      - CloudWatchFullAccess
      - AmazonEC2FullAccess
      - AmazonS3FullAccess
      - AmazonSSMFullAccess
      - AmazonSageMakerFullAccess
      - AmazonElasticMapReduceRole

INFRA:
  GITHUB_ORGANIZATION: DISHDevEx
  GITHUB_REPOSITORY: luminex-application
  GITHUB_WORKFLOW: create-emr-cft.yml
  GITHUB_EVENT_TYPE: create-emr-cft

ETL:
  S3_INPUT_BUCKET_NAME:
  AWS_REGION:
  TRANSFORMATION_FOLDER_PATH: DISHDevEx/luminex-transformation
  S3_BUCKET_INPUT_PATH:
  S3_BUCKET_TEMP_OUTPUT_PATH:
  S3_BUCKET_FINAL_OUTPUT_PATH:
  TRANSFORMATION_FOLDER: scripts/transformation/
  BOAT: luminex
  INPUT_FOLDER:

EXPERIMENT:
  META:
    NAME: MyFirstExperiment
  MODEL:
    FAMILY: resnet
    N_LAYERS: 151
    NESTED_FAMILY:
      ITEMS:
        - CloudWatchFullAccess
        - AmazonEC2FullAccess
  TRAINING:
    BATCH_SIZE: 256
    EPOCHS: 10000